var dir_4a2671b62cd17faf252e11d87b62d651 =
[
    [ "c_interface", "dir_dfe08cafcd991fb82ad7972f3984c63d.html", "dir_dfe08cafcd991fb82ad7972f3984c63d" ],
    [ "sha1", "dir_20055c2ad4924e3b3718de7ec734f8a2.html", "dir_20055c2ad4924e3b3718de7ec734f8a2" ],
    [ "srchelper", "dir_c4bb563d0b2abba964f990f8e059289b.html", "dir_c4bb563d0b2abba964f990f8e059289b" ],
    [ "Analog.h", "_analog_8h_source.html", null ],
    [ "BReverbModel.h", "_b_reverb_model_8h_source.html", null ],
    [ "config.h", "config_8h_source.html", null ],
    [ "Enumerations.h", "_enumerations_8h_source.html", null ],
    [ "File.h", "_file_8h_source.html", null ],
    [ "FileStream.h", "_file_stream_8h_source.html", null ],
    [ "globals.h", "globals_8h_source.html", null ],
    [ "internals.h", "internals_8h_source.html", null ],
    [ "LA32FloatWaveGenerator.h", "_l_a32_float_wave_generator_8h_source.html", null ],
    [ "LA32Ramp.h", "_l_a32_ramp_8h_source.html", null ],
    [ "LA32WaveGenerator.h", "_l_a32_wave_generator_8h_source.html", null ],
    [ "MemoryRegion.h", "_memory_region_8h_source.html", null ],
    [ "MidiEventQueue.h", "_midi_event_queue_8h_source.html", null ],
    [ "MidiStreamParser.h", "_midi_stream_parser_8h_source.html", null ],
    [ "mmath.h", "mmath_8h_source.html", null ],
    [ "mt32emu.h", "mt32emu_8h_source.html", null ],
    [ "Part.h", "_part_8h_source.html", null ],
    [ "Partial.h", "_partial_8h_source.html", null ],
    [ "PartialManager.h", "_partial_manager_8h_source.html", null ],
    [ "Poly.h", "_poly_8h_source.html", null ],
    [ "ROMInfo.h", "_r_o_m_info_8h_source.html", null ],
    [ "SampleRateConverter.h", "_sample_rate_converter_8h_source.html", null ],
    [ "Structures.h", "_structures_8h_source.html", null ],
    [ "Synth.h", "_synth_8h_source.html", null ],
    [ "Tables.h", "_tables_8h_source.html", null ],
    [ "TVA.h", "_t_v_a_8h_source.html", null ],
    [ "TVF.h", "_t_v_f_8h_source.html", null ],
    [ "TVP.h", "_t_v_p_8h_source.html", null ],
    [ "Types.h", "_types_8h_source.html", null ]
];