var annotated_dup =
[
    [ "Common", null, [
      [ "Array", "da/d63/class_common_1_1_array.html", null ]
    ] ],
    [ "Graphics", null, [
      [ "BaseMacWindow", "df/d19/class_graphics_1_1_base_mac_window.html", "df/d19/class_graphics_1_1_base_mac_window" ],
      [ "BdfBoundingBox", "d6/d52/struct_graphics_1_1_bdf_bounding_box.html", "d6/d52/struct_graphics_1_1_bdf_bounding_box" ],
      [ "BdfFont", "de/d24/class_graphics_1_1_bdf_font.html", "de/d24/class_graphics_1_1_bdf_font" ],
      [ "BdfFontData", "d7/d95/struct_graphics_1_1_bdf_font_data.html", "d7/d95/struct_graphics_1_1_bdf_font_data" ],
      [ "BilinearTexelBuffer", "d3/d0c/class_graphics_1_1_bilinear_texel_buffer.html", "d3/d0c/class_graphics_1_1_bilinear_texel_buffer" ],
      [ "BlittingDrawCall", "d1/d98/class_graphics_1_1_blitting_draw_call.html", "d1/d98/class_graphics_1_1_blitting_draw_call" ],
      [ "BlitTransform", "d0/dbd/struct_graphics_1_1_blit_transform.html", "d0/dbd/struct_graphics_1_1_blit_transform" ],
      [ "BorderOffsets", "df/d49/struct_graphics_1_1_border_offsets.html", "df/d49/struct_graphics_1_1_border_offsets" ],
      [ "ClearBufferDrawCall", "dc/d03/class_graphics_1_1_clear_buffer_draw_call.html", "dc/d03/class_graphics_1_1_clear_buffer_draw_call" ],
      [ "ColorComponent", "dc/ded/struct_graphics_1_1_color_component.html", null ],
      [ "ColorComponent< 0 >", "d6/db4/struct_graphics_1_1_color_component_3_010_01_4.html", null ],
      [ "ColorComponent< 1 >", "db/d01/struct_graphics_1_1_color_component_3_011_01_4.html", null ],
      [ "ColorComponent< 2 >", "de/d76/struct_graphics_1_1_color_component_3_012_01_4.html", null ],
      [ "ColorComponent< 3 >", "dd/da9/struct_graphics_1_1_color_component_3_013_01_4.html", null ],
      [ "ColorComponent< 4 >", "d0/dab/struct_graphics_1_1_color_component_3_014_01_4.html", null ],
      [ "ColorComponent< 5 >", "db/d00/struct_graphics_1_1_color_component_3_015_01_4.html", null ],
      [ "ColorComponent< 6 >", "dd/db3/struct_graphics_1_1_color_component_3_016_01_4.html", null ],
      [ "ColorComponent< 7 >", "d8/d20/struct_graphics_1_1_color_component_3_017_01_4.html", null ],
      [ "ColorComponent< 8 >", "d3/d3b/struct_graphics_1_1_color_component_3_018_01_4.html", null ],
      [ "ColorMasks", "d5/dd9/struct_graphics_1_1_color_masks.html", null ],
      [ "ColorMasks< 1555 >", "db/d7e/struct_graphics_1_1_color_masks_3_011555_01_4.html", "db/d7e/struct_graphics_1_1_color_masks_3_011555_01_4" ],
      [ "ColorMasks< 4444 >", "df/d1f/struct_graphics_1_1_color_masks_3_014444_01_4.html", "df/d1f/struct_graphics_1_1_color_masks_3_014444_01_4" ],
      [ "ColorMasks< 555 >", "d8/df6/struct_graphics_1_1_color_masks_3_01555_01_4.html", "d8/df6/struct_graphics_1_1_color_masks_3_01555_01_4" ],
      [ "ColorMasks< 5551 >", "d0/d5c/struct_graphics_1_1_color_masks_3_015551_01_4.html", "d0/d5c/struct_graphics_1_1_color_masks_3_015551_01_4" ],
      [ "ColorMasks< 565 >", "d9/dd2/struct_graphics_1_1_color_masks_3_01565_01_4.html", "d9/dd2/struct_graphics_1_1_color_masks_3_01565_01_4" ],
      [ "ColorMasks< 888 >", "de/dc9/struct_graphics_1_1_color_masks_3_01888_01_4.html", "de/dc9/struct_graphics_1_1_color_masks_3_01888_01_4" ],
      [ "ColorMasks< 8888 >", "dd/d0d/struct_graphics_1_1_color_masks_3_018888_01_4.html", "dd/d0d/struct_graphics_1_1_color_masks_3_018888_01_4" ],
      [ "Cursor", "d7/d40/class_graphics_1_1_cursor.html", "d7/d40/class_graphics_1_1_cursor" ],
      [ "CursorManager", "d4/de8/class_graphics_1_1_cursor_manager.html", "d4/de8/class_graphics_1_1_cursor_manager" ],
      [ "DrawCall", "db/d5b/class_graphics_1_1_draw_call.html", "db/d5b/class_graphics_1_1_draw_call" ],
      [ "DrawStep", "df/d09/struct_graphics_1_1_draw_step.html", "df/d09/struct_graphics_1_1_draw_step" ],
      [ "FloatPoint", "db/d24/struct_graphics_1_1_float_point.html", "db/d24/struct_graphics_1_1_float_point" ],
      [ "FloodFill", "db/df8/class_graphics_1_1_flood_fill.html", "db/df8/class_graphics_1_1_flood_fill" ],
      [ "Font", "d0/df4/class_graphics_1_1_font.html", "d0/df4/class_graphics_1_1_font" ],
      [ "FontKorean", "dd/ddd/class_graphics_1_1_font_korean.html", "dd/ddd/class_graphics_1_1_font_korean" ],
      [ "FontKoreanBase", "d0/d7a/class_graphics_1_1_font_korean_base.html", "d0/d7a/class_graphics_1_1_font_korean_base" ],
      [ "FontKoreanSVM", "dc/d80/class_graphics_1_1_font_korean_s_v_m.html", "dc/d80/class_graphics_1_1_font_korean_s_v_m" ],
      [ "FontKoreanWansung", "d9/de7/class_graphics_1_1_font_korean_wansung.html", "d9/de7/class_graphics_1_1_font_korean_wansung" ],
      [ "FontManager", "d1/dfa/class_graphics_1_1_font_manager.html", "d1/dfa/class_graphics_1_1_font_manager" ],
      [ "MacButton", "da/d79/class_graphics_1_1_mac_button.html", "da/d79/class_graphics_1_1_mac_button" ],
      [ "MacCursor", "dd/ddf/class_graphics_1_1_mac_cursor.html", "dd/ddf/class_graphics_1_1_mac_cursor" ],
      [ "MacFont", "df/d7f/class_graphics_1_1_mac_font.html", "df/d7f/class_graphics_1_1_mac_font" ],
      [ "MacFONTdata", "d0/d65/struct_graphics_1_1_mac_f_o_n_tdata.html", "d0/d65/struct_graphics_1_1_mac_f_o_n_tdata" ],
      [ "MacFontFamily", "d3/dee/class_graphics_1_1_mac_font_family.html", "d3/dee/class_graphics_1_1_mac_font_family" ],
      [ "MacFONTFont", "dd/d0c/class_graphics_1_1_mac_f_o_n_t_font.html", "dd/d0c/class_graphics_1_1_mac_f_o_n_t_font" ],
      [ "MacFontManager", "db/d93/class_graphics_1_1_mac_font_manager.html", "db/d93/class_graphics_1_1_mac_font_manager" ],
      [ "MacFontRun", "d5/dff/struct_graphics_1_1_mac_font_run.html", "d5/dff/struct_graphics_1_1_mac_font_run" ],
      [ "MacGlyph", "db/d58/struct_graphics_1_1_mac_glyph.html", "db/d58/struct_graphics_1_1_mac_glyph" ],
      [ "MacMenu", "d4/d8c/class_graphics_1_1_mac_menu.html", "d4/d8c/class_graphics_1_1_mac_menu" ],
      [ "MacMenuData", "de/d5d/struct_graphics_1_1_mac_menu_data.html", "de/d5d/struct_graphics_1_1_mac_menu_data" ],
      [ "MacPlotData", "d2/d18/struct_graphics_1_1_mac_plot_data.html", "d2/d18/struct_graphics_1_1_mac_plot_data" ],
      [ "MacText", "d7/d1a/class_graphics_1_1_mac_text.html", "d7/d1a/class_graphics_1_1_mac_text" ],
      [ "MacTextLine", "db/da7/struct_graphics_1_1_mac_text_line.html", "db/da7/struct_graphics_1_1_mac_text_line" ],
      [ "MacTextWindow", "df/de3/class_graphics_1_1_mac_text_window.html", "df/de3/class_graphics_1_1_mac_text_window" ],
      [ "MacWidget", "d8/dbf/class_graphics_1_1_mac_widget.html", "d8/dbf/class_graphics_1_1_mac_widget" ],
      [ "MacWindow", "d5/d01/class_graphics_1_1_mac_window.html", "d5/d01/class_graphics_1_1_mac_window" ],
      [ "MacWindowBorder", "d6/d0a/class_graphics_1_1_mac_window_border.html", "d6/d0a/class_graphics_1_1_mac_window_border" ],
      [ "MacWindowManager", "d7/d16/class_graphics_1_1_mac_window_manager.html", "d7/d16/class_graphics_1_1_mac_window_manager" ],
      [ "ManagedSurface", "d8/d0f/class_graphics_1_1_managed_surface.html", "d8/d0f/class_graphics_1_1_managed_surface" ],
      [ "Mode", "d6/d50/struct_graphics_1_1_mode.html", "d6/d50/struct_graphics_1_1_mode" ],
      [ "NearestTexelBuffer", "d6/dab/class_graphics_1_1_nearest_texel_buffer.html", "d6/dab/class_graphics_1_1_nearest_texel_buffer" ],
      [ "NinePatchBitmap", "d0/d14/class_graphics_1_1_nine_patch_bitmap.html", "d0/d14/class_graphics_1_1_nine_patch_bitmap" ],
      [ "NinePatchMark", "d3/d8d/struct_graphics_1_1_nine_patch_mark.html", "d3/d8d/struct_graphics_1_1_nine_patch_mark" ],
      [ "NinePatchSide", "d9/dba/class_graphics_1_1_nine_patch_side.html", "d9/dba/class_graphics_1_1_nine_patch_side" ],
      [ "PixelBuffer", "d4/dda/class_graphics_1_1_pixel_buffer.html", "d4/dda/class_graphics_1_1_pixel_buffer" ],
      [ "PixelFormat", "dc/d65/struct_graphics_1_1_pixel_format.html", "dc/d65/struct_graphics_1_1_pixel_format" ],
      [ "RasterizationDrawCall", "d9/d32/class_graphics_1_1_rasterization_draw_call.html", "d9/d32/class_graphics_1_1_rasterization_draw_call" ],
      [ "RendererTypeDescription", "d2/d5b/struct_graphics_1_1_renderer_type_description.html", "d2/d5b/struct_graphics_1_1_renderer_type_description" ],
      [ "RowReader", "d6/dc5/class_graphics_1_1_row_reader.html", "d6/dc5/class_graphics_1_1_row_reader" ],
      [ "RowWriter", "d8/d5d/class_graphics_1_1_row_writer.html", "d8/d5d/class_graphics_1_1_row_writer" ],
      [ "Screen", "d3/d76/class_graphics_1_1_screen.html", "d3/d76/class_graphics_1_1_screen" ],
      [ "SelectedText", "dd/dd3/struct_graphics_1_1_selected_text.html", "dd/dd3/struct_graphics_1_1_selected_text" ],
      [ "Surface", "da/dfe/struct_graphics_1_1_surface.html", "da/dfe/struct_graphics_1_1_surface" ],
      [ "SurfaceDeleter", "d2/d4c/struct_graphics_1_1_surface_deleter.html", "d2/d4c/struct_graphics_1_1_surface_deleter" ],
      [ "TexelBuffer", "d2/d15/class_graphics_1_1_texel_buffer.html", "d2/d15/class_graphics_1_1_texel_buffer" ],
      [ "TransformStruct", "d0/d03/struct_graphics_1_1_transform_struct.html", "d0/d03/struct_graphics_1_1_transform_struct" ],
      [ "TransformTools", "de/d4b/class_graphics_1_1_transform_tools.html", null ],
      [ "TransparentSurface", "d6/dfd/struct_graphics_1_1_transparent_surface.html", "d6/dfd/struct_graphics_1_1_transparent_surface" ],
      [ "VectorRenderer", "d3/d41/class_graphics_1_1_vector_renderer.html", "d3/d41/class_graphics_1_1_vector_renderer" ],
      [ "VectorRendererAA", "db/dd4/class_graphics_1_1_vector_renderer_a_a.html", "db/dd4/class_graphics_1_1_vector_renderer_a_a" ],
      [ "VectorRendererSpec", "d3/dd1/class_graphics_1_1_vector_renderer_spec.html", "d3/dd1/class_graphics_1_1_vector_renderer_spec" ],
      [ "WinCursorGroup", "d2/d58/struct_graphics_1_1_win_cursor_group.html", "d2/d58/struct_graphics_1_1_win_cursor_group" ],
      [ "WinFont", "d0/da9/class_graphics_1_1_win_font.html", "d0/da9/class_graphics_1_1_win_font" ],
      [ "WinFontDirEntry", "d5/d62/struct_graphics_1_1_win_font_dir_entry.html", "d5/d62/struct_graphics_1_1_win_font_dir_entry" ],
      [ "YUVToRGBManager", "d7/d90/class_graphics_1_1_y_u_v_to_r_g_b_manager.html", "d7/d90/class_graphics_1_1_y_u_v_to_r_g_b_manager" ],
      [ "ZoomBox", "db/d24/struct_graphics_1_1_zoom_box.html", "db/d24/struct_graphics_1_1_zoom_box" ]
    ] ],
    [ "OpenGL", null, [
      [ "ContextGL", "d0/d4d/class_open_g_l_1_1_context_g_l.html", "d0/d4d/class_open_g_l_1_1_context_g_l" ],
      [ "FixedSurfaceRenderer", "dd/db7/class_open_g_l_1_1_fixed_surface_renderer.html", "dd/db7/class_open_g_l_1_1_fixed_surface_renderer" ],
      [ "ShaderGL", "d1/d43/class_open_g_l_1_1_shader_g_l.html", "d1/d43/class_open_g_l_1_1_shader_g_l" ],
      [ "SurfaceRenderer", "d3/d46/class_open_g_l_1_1_surface_renderer.html", "d3/d46/class_open_g_l_1_1_surface_renderer" ],
      [ "TiledSurface", "df/d23/class_open_g_l_1_1_tiled_surface.html", "df/d23/class_open_g_l_1_1_tiled_surface" ],
      [ "VertexAttrib", "d3/d53/struct_open_g_l_1_1_vertex_attrib.html", "d3/d53/struct_open_g_l_1_1_vertex_attrib" ]
    ] ],
    [ "TinyGL", null, [
      [ "Buffer", "d7/d3f/struct_tiny_g_l_1_1_buffer.html", "d7/d3f/struct_tiny_g_l_1_1_buffer" ],
      [ "FrameBuffer", "d0/dac/struct_tiny_g_l_1_1_frame_buffer.html", "d0/dac/struct_tiny_g_l_1_1_frame_buffer" ],
      [ "GLContext", "df/d79/struct_tiny_g_l_1_1_g_l_context.html", "df/d79/struct_tiny_g_l_1_1_g_l_context" ],
      [ "GLImage", "d2/dab/struct_tiny_g_l_1_1_g_l_image.html", "d2/dab/struct_tiny_g_l_1_1_g_l_image" ],
      [ "GLLight", "d8/dec/struct_tiny_g_l_1_1_g_l_light.html", "d8/dec/struct_tiny_g_l_1_1_g_l_light" ],
      [ "GLList", "d5/d64/struct_tiny_g_l_1_1_g_l_list.html", "d5/d64/struct_tiny_g_l_1_1_g_l_list" ],
      [ "GLMaterial", "d3/d41/struct_tiny_g_l_1_1_g_l_material.html", "d3/d41/struct_tiny_g_l_1_1_g_l_material" ],
      [ "GLParam", "d7/d21/union_tiny_g_l_1_1_g_l_param.html", "d7/d21/union_tiny_g_l_1_1_g_l_param" ],
      [ "GLParamBuffer", "d9/d80/struct_tiny_g_l_1_1_g_l_param_buffer.html", "d9/d80/struct_tiny_g_l_1_1_g_l_param_buffer" ],
      [ "GLSharedState", "d6/d69/struct_tiny_g_l_1_1_g_l_shared_state.html", "d6/d69/struct_tiny_g_l_1_1_g_l_shared_state" ],
      [ "GLSpecBuf", "d9/dd1/struct_tiny_g_l_1_1_g_l_spec_buf.html", "d9/dd1/struct_tiny_g_l_1_1_g_l_spec_buf" ],
      [ "GLTexture", "d7/d3c/struct_tiny_g_l_1_1_g_l_texture.html", "d7/d3c/struct_tiny_g_l_1_1_g_l_texture" ],
      [ "GLVertex", "de/d56/struct_tiny_g_l_1_1_g_l_vertex.html", "de/d56/struct_tiny_g_l_1_1_g_l_vertex" ],
      [ "GLViewport", "de/d6d/struct_tiny_g_l_1_1_g_l_viewport.html", "de/d6d/struct_tiny_g_l_1_1_g_l_viewport" ],
      [ "LinearAllocator", "d8/d4c/class_tiny_g_l_1_1_linear_allocator.html", "d8/d4c/class_tiny_g_l_1_1_linear_allocator" ],
      [ "Matrix4", "d8/dbe/class_tiny_g_l_1_1_matrix4.html", "d8/dbe/class_tiny_g_l_1_1_matrix4" ],
      [ "Vector3", "d1/de1/class_tiny_g_l_1_1_vector3.html", "d1/de1/class_tiny_g_l_1_1_vector3" ],
      [ "Vector4", "d9/d75/class_tiny_g_l_1_1_vector4.html", "d9/d75/class_tiny_g_l_1_1_vector4" ],
      [ "ZBufferPoint", "d6/db9/struct_tiny_g_l_1_1_z_buffer_point.html", "d6/db9/struct_tiny_g_l_1_1_z_buffer_point" ]
    ] ],
    [ "PaletteManager", "da/d78/class_palette_manager.html", "da/d78/class_palette_manager" ]
];