var searchData=
[
  ['aac_2eh',['aac.h',['../d7/dff/aac_8h.html',1,'']]],
  ['abortfade',['abortFade',['../d6/d1d/class_midi_driver___m_t32_g_m.html#af51c863d9fdff43f088d6624c437c4b1',1,'MidiDriver_MT32GM::abortFade(FadeAbortType abortType=FADE_ABORT_TYPE_END_VOLUME)'],['../d6/d1d/class_midi_driver___m_t32_g_m.html#ab2e5e2eceaf38c3f6c878898023792c5',1,'MidiDriver_MT32GM::abortFade(uint8 source, FadeAbortType abortType=FADE_ABORT_TYPE_END_VOLUME)']]],
  ['abstractfile',['AbstractFile',['../d5/d0b/class_m_t32_emu_1_1_abstract_file.html',1,'MT32Emu']]],
  ['activenote',['ActiveNote',['../da/dff/struct_midi_driver___m_t32_g_m_1_1_active_note.html',1,'MidiDriver_MT32GM']]],
  ['addactivenote',['addActiveNote',['../d6/d1d/class_midi_driver___m_t32_g_m.html#a635888bffabec789a0cb6d41ecd438cc',1,'MidiDriver_MT32GM']]],
  ['addframes',['addFrames',['../df/dec/class_audio_1_1_timestamp.html#ab46f4f62189a6f1bde416e8e952aa0fc',1,'Audio::Timestamp']]],
  ['addintern',['addIntern',['../df/dec/class_audio_1_1_timestamp.html#a89c0a84c4e5cf236a2163d85476316c2',1,'Audio::Timestamp']]],
  ['addmsecs',['addMsecs',['../df/dec/class_audio_1_1_timestamp.html#a935ccd4a2789088d91edaeb8265c445f',1,'Audio::Timestamp']]],
  ['adpcm_2eh',['adpcm.h',['../d0/d5e/adpcm_8h.html',1,'']]],
  ['adpcmchannelstatus',['ADPCMChannelStatus',['../d2/df7/struct_audio_1_1_m_s___a_d_p_c_m_stream_1_1_a_d_p_c_m_channel_status.html',1,'Audio::MS_ADPCMStream']]],
  ['adpcmstatus',['ADPCMStatus',['../d9/d7b/struct_audio_1_1_a_d_p_c_m_stream_1_1_a_d_p_c_m_status.html',1,'Audio::ADPCMStream']]],
  ['adpcmstream',['ADPCMStream',['../d9/dd7/class_audio_1_1_a_d_p_c_m_stream.html',1,'Audio']]],
  ['aiff_2eh',['aiff.h',['../d6/d87/aiff_8h.html',1,'']]],
  ['allocatesourcechannels',['allocateSourceChannels',['../d6/d1d/class_midi_driver___m_t32_g_m.html#ad21b26a9fc83d5786c9d22bc28fad0f3',1,'MidiDriver_MT32GM']]],
  ['analog',['Analog',['../d4/d47/class_m_t32_emu_1_1_analog.html',1,'MT32Emu']]],
  ['apple_5fadpcmstream',['Apple_ADPCMStream',['../dc/d0c/class_audio_1_1_apple___a_d_p_c_m_stream.html',1,'Audio']]],
  ['arrayfile',['ArrayFile',['../d6/d6e/class_m_t32_emu_1_1_array_file.html',1,'MT32Emu']]],
  ['audio',['Audio',['../dc/d26/namespace_audio.html',1,'Audio'],['../d1/d4d/group__audio.html',1,'(Global Namespace)']]],
  ['audio3do_5fadp4_5fstream',['Audio3DO_ADP4_Stream',['../df/dd3/class_audio_1_1_audio3_d_o___a_d_p4___stream.html',1,'Audio']]],
  ['audio3do_5fsdx2_5fstream',['Audio3DO_SDX2_Stream',['../db/d3c/class_audio_1_1_audio3_d_o___s_d_x2___stream.html',1,'Audio']]],
  ['audio_5f3do_5fadp4_5fpersistentspace',['audio_3DO_ADP4_PersistentSpace',['../d8/dff/struct_audio_1_1audio__3_d_o___a_d_p4___persistent_space.html',1,'Audio']]],
  ['audio_5f3do_5fsdx2_5fpersistentspace',['audio_3DO_SDX2_PersistentSpace',['../d1/db4/struct_audio_1_1audio__3_d_o___s_d_x2___persistent_space.html',1,'Audio']]],
  ['audio_20streams',['Audio streams',['../db/d71/group__audio__audiostream.html',1,'']]],
  ['audiosampledesc',['AudioSampleDesc',['../d4/d4d/class_audio_1_1_quick_time_audio_decoder_1_1_audio_sample_desc.html',1,'Audio::QuickTimeAudioDecoder']]],
  ['audiostream',['AudioStream',['../d9/d5a/class_audio_1_1_audio_stream.html',1,'Audio']]]
];
